name: CI

on:
  push:
    branches:
      - '*'  # Déclenchement sur toutes les branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Se connecter à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire l'image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/site-html-nginx:latest .

      - name: Pousser l'image vers DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/site-html-nginx:latest

      - name: Message de fin
        run: echo "✅ Image Docker construite et poussée avec succès !"
